### ISSUE TITLE
Python files have 1.1 set to __version__

### ISSUE THREAD

**Issue by jeez** [quark-mcu/qm-bootloader#6]
After checking some files, I noticed the below:
- tools/sysupdate/qm_manage.py:47:**version** = "1.1"
- tools/sysupdate/qmfmlib/**init**.py:58:**version** = "1.1"

@dalessan is that correct or should they say 1.3 instead?

**Comment by dalessan** [comment]
Nice catch, they should be updated. I will prepare a pull request later today.

**Comment by dalessan** [comment]
Sorry, I completely forgot about this :(

I just created the pull request: #10

**Comment by jeez** [comment]
MERGED #10 . Closing this issue. Thanks!
