### ISSUE TITLE
Need to do mass erase before flashing quark_se_rom_fm_hmac.bin

### ISSUE THREAD

**Issue by QiuPeiyang** [quark-mcu/qm-bootloader#8]
After flashing quark_se_rom_fm_hmac.bin, if don't do mass erase, it will have nothing from the uart console.
This is not included in the README.rst and user might be confused.

**Comment by sharronliu** [comment]
Peiyang, could you share your findings on how to eliminate this? I learnt you managed to figure out the tricky step.

**Comment by QiuPeiyang** [comment]
This can be done using openocd, just run the following commands using openocd:
> reset halt
> mass_erase
 
From my side, I use the following command when I am in zephyr root dir:
/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/openocd -s /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts -f ./boards/x86/quark_se_c1000_devboard/support/openocd.cfg -c init -c mass_erase

On quark se you should get the following output:
0xb0100014: 00000001 
0xb0200014: 00000001

**Comment by sharronliu** [comment]
OK. From my side, I do below step before "monitor load_image"
<gdb> monitor mass_erase

**Comment by dalessan** [comment]
Thanks for reporting this. I created a pull request (#9) to updated the README with the missing step. Can you please have a look at it? Just to ensure that you are fine with the update.

I'll close this issue as soon as the pull request is merged.

Thanks again :)

**Comment by jeez** [comment]
PR #9 merged. @QiuPeiyang @sharronliu are you fine with it being documented that way?
If yes, please close this issue.

thanks

**Comment by QiuPeiyang** [comment]
The README documentation has been updated. Close this issue.
